### ISSUE TITLE
TODO: Product detail

### ISSUE THREAD

**Issue by esparen** [barbaracalderon/minimarket#10]
- [x] Ao clicar em adicionar o produto ao carrinho, remover o alerta, e navegar até a pagina do carrinho
- [x] refatorar para que o componente busque as informações do produdo passado por parametro na url (id) no serviço de produtos. Remover o produto fixo em product-view.component.ts
- [x] refinar o layout / css da pagina
