### ISSUE TITLE
TODO: integrações

### ISSUE THREAD

**Issue by barbaracalderon** [barbaracalderon/minimarket#11]
Exercício 08 - Integrações

### Home:

- [x]         Teremos um endpoint para buscar os produtos mais vendidos da semana, e o seu retorno populará a sessão Mais vendido da semana;
- [x]         Teremos um endpoint para buscar os produtos em ofertas e o seu retorno populará a sessão Ofertas do dia.

### Detalhes do Produto:

- [x]         Teremos um endpoint que irá receber o produto selecionado e retornará os detalhes daquele produto;
- [x]         Teremos um endpoint de comentários que irá receber o produto selecionado e retornará todos os comentários daquele produto;
- [x]         Quando o botão Adicionar ao Carrinho for clicado, armazene o produto selecionado em um estado global representando os itens do carrinho.
