### ISSUE TITLE
TODO: Home

### ISSUE THREAD

**Issue by esparen** [barbaracalderon/minimarket#12]
- [x]  Buscar os produtos da seção "**Mais vendidos**" no endpoint do exercicio 8: integrações:
Está escrito: "_Teremos um endpoint para buscar os produtos mais vendidos da semana, e o seu retorno populará a sessão Mais vendido da semana_"
- [x]  Buscar os produtos da seção "**Ofertas da semana**" no endpoint do exercicio 8: integrações:
2.1. Está escrito: "_Teremos um endpoint para buscar os produtos em ofertas e o seu retorno populará a sessão Ofertas do dia._"
- [x]  refinar css da página
